version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bplanner_db
    environment:
      POSTGRES_USER: bbd_graduser
      POSTGRES_PASSWORD: bbdpassword
      POSTGRES_DB: bplannerdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
